### ISSUE TITLE
Please Update the current week task 4

### ISSUE THREAD

**Issue by rmndkyl** [Widiskel/initia-daily-bot#10]
![image](https://github.com/Widiskel/initia-daily-bot/assets/99118244/f747c31d-adac-4768-82cb-44ad1ad6e7d6)
this is the current task

**Comment by Widiskel** [comment]
added,  but still experimental, i still find a way to generate the timeout_timestamp on initia ibc relay. if it does'nt work then just complete it manually, it just weekkly exp quest. im also added some feature.
