### ISSUE TITLE
report

### ISSUE THREAD

**Issue by matasanga9** [Widiskel/initia-daily-bot#12]
ERROR : 1-13
SUCCESS : 14-finish

thanks

![nit](https://github.com/Widiskel/initia-daily-bot/assets/168496965/95c4600e-4713-4be7-9550-a9899b9504d3)

**Comment by Widiskel** [comment]
if it RPC error then no way i can handle it, and about Bot feature no 10-13 it still experimental and mostly it will got Rpc error. i think no problem for feature no 1-9 

Remember to keep the bot up to date
