### ISSUE TITLE
error

### ISSUE THREAD

**Issue by satinex** [Widiskel/initia-daily-bot#15]
![Screenshot 2024-06-09 025824](https://github.com/Widiskel/initia-daily-bot/assets/51521535/5fd55bda-2b67-4628-b6d8-e1bd40de7d25)
![Screenshot 2024-06-09 025824](https://github.com/Widiskel/initia-daily-bot/assets/51521535/5fd55bda-2b67-4628-b6d8-e1bd40de7d25)
![Screenshot 2024-06-09 025824](https://github.com/Widiskel/initia-daily-bot/assets/51521535/5fd55bda-2b67-4628-b6d8-e1bd40de7d25)

**Comment by Widiskel** [comment]
check feature no 20, make sure it success and check on you initia account profile, if you can see init staked on omninode, the move stake must be ok.

and if it still error, look at ```src/module/initia/initia.js``` line 759 , change the amount to ```100000uinit```

**Comment by Widiskel** [comment]
if it OK already, don't forget to close the issue

**Comment by Widiskel** [comment]
new update released regarding to this error , go update
