### ISSUE TITLE
Just show Initia Task Runner ! {NOTHING HAPPEN}

### ISSUE THREAD

**Issue by 0xsiwant** [Widiskel/initia-daily-bot#2]
![image](https://github.com/Widiskel/initia-daily-bot/assets/129720275/73d86a96-fe11-4ef5-a589-fe862219e67a)

Thiis erorr or what ? Just show Initia Task Runner ! {NOTHING HAPPEN}

**Comment by Widiskel** [comment]
ahh, its because our team try to add scheduler feature, do `git pull` and try again with `npm run start`

**Comment by imposteruck** [comment]
thats my mistake. sorry 🤣
