### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'amount')

### ISSUE THREAD

**Issue by QuantumLeap-us** [Widiskel/initia-daily-bot#6]
> node index.js

201.861879 uinit

TypeError: Cannot read properties of undefined (reading 'amount')
    at file:///F:/initia-daily-bot/index.js:14:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///F:/initia-daily-bot/index.js:13:11
    at async file:///F:/initia-daily-bot/index.js:10:7

**Comment by Widiskel** [comment]
pull new update, its fixed already
