### ISSUE TITLE
Did you test for reliability? He still doesn't work.

### ISSUE THREAD

**Issue by QuantumLeap-us** [Widiskel/initia-daily-bot#7]
PS F:\initia-daily-bot> git pull
Updating 80a45b4..b2dacdd
Fast-forward
 Readme.md                           |   5 +-
 index.js                            |  18 +++-
 src/module/initia/initia.js         | 193 ++++++++++++++++++++++++------------
 src/module/initia/initia_routine.js |  62 +++++++-----
 src/utils/constant.js               |  27 ++++-
 src/utils/enum/pair.js              |  15 +++
 test/test.js                        |  68 +++++++++++--
 7 files changed, 278 insertions(+), 110 deletions(-)
 create mode 100644 src/utils/enum/pair.js
PS F:\initia-daily-bot> npm run start

> initia-daily-bot@1.0.0 start
> node index.js

TypeError: Cannot read properties of undefined (reading 'amount')
    at file:///F:/initia-daily-bot/index.js:15:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///F:/initia-daily-bot/index.js:14:11
    at async file:///F:/initia-daily-bot/index.js:11:7

**Comment by Widiskel** [comment]
it work fine on me , did you fill your account.js correctly?

**Comment by QuantumLeap-us** [comment]
![image](https://github.com/Widiskel/initia-daily-bot/assets/40482494/946e8b33-56f5-4718-8aa9-0a9197345af9)
I think that's right. Address and private key.

**Comment by Widiskel** [comment]
> ![image](https://private-user-images.githubusercontent.com/40482494/336082899-946e8b33-56f5-4718-8aa9-0a9197345af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzAxNjksIm5iZiI6MTcxNzQyOTg2OSwicGF0aCI6Ii80MDQ4MjQ5NC8zMzYwODI4OTktOTQ2ZThiMzMtNTZmNS00NzE4LThhYTktMGE5MTk3MzQ1YWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE1NTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTNkNDQ5MjNiMzk5ZWQ4ODc2NzViNzc5OTNiZGNiYTBiYjlhM2EwZmU5NDI0ZjMzMjY4Y2NkYWFlZTc3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yCih-SVoSmKoE_DRxK7TRgAqxDrJdktDh8zQ9lth0Zk) I think that's right. Address and private key.

thats right, did you request for faucet already ? it required GAS token and Initia Token.

and regarding the error im already add the error handler

**Comment by QuantumLeap-us** [comment]
successful
